### ISSUE TITLE
Design: Meta

### ISSUE THREAD

**Issue by BrainBlasted** [BrainBlasted/Trumpet#8]
This is a tracking issue for design tasks. Process inspired by [a GUADEC 2015 talk](https://www.youtube.com/watch?v=F-kcc9-5cOQ).

- [ ]  Determine the scope of the app (what to include/exclude) (#9)
- [ ] Research apps for design inspiration
- [ ] Create and review mockups
